version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONF_PATH: configs/app_conf_docker.yml
    restart: always
    environment:
      GIT_HASH: $GIT_HASH
    ports:
      - 8012:8000
    networks:
      - app-network
    command: [ "/app/binary", "--config", "configs/app_conf_docker.yml" ]

#Docker Networks
networks:
  app-network:
    driver: bridge